// AKN-PT Editor — smoke tests (run from project root with Node)
// Validates that the XML generated by the editor passes XSD + Schematron.
//
// Usage:
//   node editor/smoke-test.js
//   python -m akn_pt batch editor/.smoke-output
//
// EUPL-1.2
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname);
const OUT = path.join(ROOT, '.smoke-output');
fs.mkdirSync(OUT, { recursive: true });

function loadFile(rel) {
  const code = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  eval(`(function() { ${code};
    if (typeof newDocument !== 'undefined') global.newDocument = newDocument;
    if (typeof ACT_TYPES !== 'undefined') global.ACT_TYPES = ACT_TYPES;
    if (typeof FORMULAS !== 'undefined') global.FORMULAS = FORMULAS;
    if (typeof AknExport !== 'undefined') global.AknExport = AknExport;
    if (typeof ImportParser !== 'undefined') global.ImportParser = ImportParser;
    if (typeof References !== 'undefined') { global.References = References; globalThis.References = References; }
    if (typeof Amendment !== 'undefined') { global.Amendment = Amendment; globalThis.Amendment = Amendment; }
    if (typeof Preview !== 'undefined') { global.Preview = Preview; globalThis.Preview = Preview; }
    if (typeof Diff !== 'undefined') { global.Diff = Diff; globalThis.Diff = Diff; }
    if (typeof LodaInline !== 'undefined') { global.LodaInline = LodaInline; globalThis.LodaInline = LodaInline; }
    if (typeof BluebellPt !== 'undefined') { global.BluebellPt = BluebellPt; globalThis.BluebellPt = BluebellPt; }
    if (typeof DreMock !== 'undefined') { global.DreMock = DreMock; globalThis.DreMock = DreMock; }
    // expor para todos os módulos (akn-export precisa de ler References no fecho global)
    if (typeof AknExport !== 'undefined') globalThis.AknExport = AknExport;
  })();`);
}
loadFile('js/templates.js');
loadFile('js/references.js');  // tem de carregar antes do akn-export para o xmlText resolver
loadFile('js/dre-mock.js');
loadFile('js/akn-export.js');
loadFile('js/preview.js');
loadFile('js/diff.js');
loadFile('js/amendment.js');
loadFile('js/loda-inline.js');
loadFile('js/bluebell-pt.js');
loadFile('js/import-parser.js');

// State precisa de localStorage (shim) e ignora Editor.refresh (guard typeof).
const _mem = {};
global.localStorage = {
  getItem: (k) => _mem[k] || null,
  setItem: (k, v) => { _mem[k] = String(v); },
  removeItem: (k) => { delete _mem[k]; },
};
loadFile('js/state.js');
// expor State (definido via IIFE em state.js)
eval(fs.readFileSync(path.join(ROOT, 'js/state.js'), 'utf8') + '\nglobal.State = State;');

const cases = [
  {
    name: 'dec-lei-simple',
    setup(d) {
      d.number = '99'; d.year = 2026;
      d.shortTitle = 'Diploma de teste exportado pelo editor.';
      d.adoptionDate = '2026-03-10';
      d.publicationDate = '2026-03-15';
      d.docDate = '2026-03-15'; d.docDateText = '15 de marco';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'O presente DL estabelece o regime.';
      d.signatures = [
        { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-03-10' },
        { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-03-12' },
      ];
    },
    type: 'dec-lei',
  },
  {
    name: 'dec-lei-with-footprint',
    setup(d) {
      d.number = '300'; d.year = 2026;
      d.shortTitle = 'Diploma com pegada legislativa (pos 2026-07-27).';
      d.adoptionDate = '2026-08-01';
      d.publicationDate = '2026-08-15';
      d.docDate = '2026-08-15'; d.docDateText = '15 de agosto';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'O presente DL estabelece X.';
      d.signatures = [
        { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-08-01' },
        { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-08-10' },
      ];
      d.workflow = [
        { id: 'step_1', refersTo: 'iniciativa', date: '2026-05-01', source: 'governo', description: 'Iniciativa.', inputs: [] },
        { id: 'step_2', refersTo: 'consulta-publica', date: '2026-06-01', source: 'dapl', description: 'Consulta publica.',
          inputs: [{ id: 'input_1', date: '2026-06-15', source: 'org-cip', type: 'contributo-consulta-publica', description: 'CIP.' }],
        },
        { id: 'step_3', refersTo: 'aprovacao-cm', date: '2026-08-01', source: 'cm', description: 'CM.', inputs: [] },
        { id: 'step_4', refersTo: 'publicacao', date: '2026-08-15', source: 'dre', description: 'DR.', inputs: [] },
      ];
    },
    type: 'dec-lei',
  },
  {
    name: 'lei-simple',
    setup(d) {
      d.number = '15'; d.year = 2026;
      d.shortTitle = 'Lei de teste do editor AKN-PT.';
      d.adoptionDate = '2026-02-01';
      d.publicationDate = '2026-02-10';
      d.docDate = '2026-02-10'; d.docDateText = '10 de fevereiro';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'A presente lei estabelece o regime.';
      d.signatures = [
        { role: 'signature', as: 'presidente-ar', name: 'PAR', date: '2026-02-01' },
        { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-02-05' },
        { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-02-08' },
      ];
    },
    type: 'lei',
  },
  {
    name: 'portaria-simple',
    setup(d) {
      d.number = '100'; d.year = 2026;
      d.shortTitle = 'Portaria de teste — regulamento de modelo.';
      d.adoptionDate = '2026-05-01';
      d.publicationDate = '2026-05-05';
      d.docDate = '2026-05-05'; d.docDateText = '5 de maio';
      d.habilitante = 'https://eli.gov.pt/eli/pt/dec-lei/2025/1/pt';
      d.habilitanteLabel = 'Decreto-Lei n.o 1/2025, de 5 de novembro';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'A presente portaria aprova o modelo.';
      d.signatures = [{ role: 'signature', as: 'ministro', name: 'Ministro X', date: '2026-05-01' }];
    },
    type: 'portaria',
  },
  {
    name: 'rcm-simple',
    setup(d) {
      d.number = '50'; d.year = 2026;
      d.shortTitle = 'Aprova plano nacional X.';
      d.adoptionDate = '2026-04-10';
      d.publicationDate = '2026-04-15';
      d.docDate = '2026-04-15'; d.docDateText = '15 de abril';
      d.body.items[0].content = 'Aprovar o Plano Nacional X.';
      d.signatures = [{ role: 'signature', as: 'primeiro-ministro', name: 'PM', date: '2026-04-10' }];
    },
    type: 'res-cm',
  },
  {
    name: 'dlr-acores',
    setup(d) {
      d.number = '5'; d.year = 2026;
      d.country = 'pt-20';
      d.shortTitle = 'Aprova regime regional X dos Acores.';
      d.adoptionDate = '2026-02-10';
      d.publicationDate = '2026-02-20';
      d.docDate = '2026-02-20'; d.docDateText = '20 de fevereiro';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'O presente DLR aprova o regime X.';
      d.signatures = [
        { role: 'signature', as: 'presidente-alra', name: 'PALRA', date: '2026-02-10' },
        { role: 'promulgation', as: 'representante-republica-acores', name: 'RR', date: '2026-02-15' },
      ];
    },
    type: 'dlr',
  },
];

let n_ok = 0, n_fail = 0;
console.log(`Generating ${cases.length} test files (templates) + 1 imported in ${OUT}/\n`);

// 1. Tests from rich templates with user overrides
for (const c of cases) {
  try {
    const doc = global.newDocument(c.type);
    c.setup(doc);
    const xml = global.AknExport.toXml(doc);
    const file = path.join(OUT, `${c.name}.akn.xml`);
    fs.writeFileSync(file, xml);
    console.log(`  OK   ${c.name}.akn.xml  (${xml.length} bytes)`);
    n_ok++;
  } catch (e) {
    console.log(`  FAIL ${c.name}: ${e.message}`);
    n_fail++;
  }
}

// 1bis. DL with subalineas (i, ii, iii) nested under an alinea — exercita point recursivo
try {
  const doc = global.newDocument('dec-lei');
  doc.number = '101'; doc.year = 2026;
  doc.shortTitle = 'Diploma de teste com subalineas.';
  doc.adoptionDate = '2026-03-01'; doc.publicationDate = '2026-03-05';
  doc.docDate = '2026-03-05'; doc.docDateText = '5 de marco';
  // Replace article 2 (Definições) paragraphs with one that has nested subalineas
  doc.body.items[1].paragraphs[0].subPoints = [
    { id: 'art_2__para_1__lit_a', num: 'a)', content: 'Item primeiro;', subPoints: [] },
    { id: 'art_2__para_1__lit_b', num: 'b)', content: 'Item segundo, designadamente:', subPoints: [
      { id: 'art_2__para_1__lit_b__sublit_i', num: 'i)', content: 'sub-item 1;' },
      { id: 'art_2__para_1__lit_b__sublit_ii', num: 'ii)', content: 'sub-item 2;' },
      { id: 'art_2__para_1__lit_b__sublit_iii', num: 'iii)', content: 'sub-item 3.' },
    ]},
    { id: 'art_2__para_1__lit_c', num: 'c)', content: 'Item terceiro.', subPoints: [] },
  ];
  doc.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-03-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-03-03' },
  ];
  const xml = global.AknExport.toXml(doc);
  fs.writeFileSync(path.join(OUT, 'dec-lei-with-subalineas.akn.xml'), xml);
  console.log(`  OK   dec-lei-with-subalineas.akn.xml  (${xml.length} bytes; <point> com <list> aninhada)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL dec-lei-with-subalineas: ${e.message}`);
  n_fail++;
}

// 2. Import test: parse unmarked Portaria text and export
const portariaText = `Portaria n.º 249/2021
de 22 de novembro
Regulamenta o regime de apoio extraordinario as micro e pequenas empresas afetadas pela crise energetica.

O Decreto-Lei n.º 56/2021, de 30 de junho, estabeleceu o regime juridico de apoios extraordinarios.

Importa, por isso, fixar as condicoes de acesso.

Manda o Governo, pelo Ministro da Economia, ao abrigo do disposto no n.º 3 do artigo 8.º do Decreto-Lei n.º 56/2021, de 30 de junho, o seguinte:

Artigo 1.º
Objeto
A presente portaria regulamenta o regime.

Artigo 2.º
Beneficiarios
1 - Podem aceder ao apoio as empresas que cumulativamente:
a) Sejam micro ou pequenas empresas;
b) Demonstrem quebra de margem superior a 25%;
c) Tenham a situacao tributaria regularizada.

Artigo 3.º
Entrada em vigor
A presente portaria entra em vigor no dia seguinte ao da sua publicacao.`;

try {
  const parsed = global.ImportParser.parse(portariaText);
  const doc = global.ImportParser.toDocState(parsed);
  const xml = global.AknExport.toXml(doc);
  const file = path.join(OUT, 'imported-portaria.akn.xml');
  fs.writeFileSync(file, xml);
  console.log(`  OK   imported-portaria.akn.xml  (${xml.length} bytes; parser → exporter)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL imported-portaria: ${e.message}`);
  n_fail++;
}

// 3. Test inserting articles at arbitrary positions (insert/move feature)
try {
  // Usa o State real (com localStorage shim) para exercer insertArticleAt + renumberArticles.
  const doc = global.newDocument('dec-lei');
  doc.number = '500'; doc.year = 2026;
  doc.shortTitle = 'Exemplo de articulado com insercoes e renumeracao.';
  doc.adoptionDate = '2026-06-01'; doc.publicationDate = '2026-06-05';
  doc.docDate = '2026-06-05'; doc.docDateText = '5 de junho';
  doc.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  global.State.init(doc);
  // Inserir artigo entre art_2 e art_3 → renumera todos, novo fica art_3.
  global.State.insertArticleAt(doc.body.items[1].id);
  const newArt = doc.body.items[2];
  global.State.updateArticle(newArt.id, { heading: 'Disposicao Inserida' });
  global.State.updateParagraph(newArt.paragraphs[0].id, newArt.id, { content: 'Conteudo inserido por renumeracao.' });
  const ids = doc.body.items.map(a => a.id).join(',');
  const expect = ['art_1','art_2','art_3','art_4','art_5'].join(',');
  if (ids !== expect) throw new Error(`renumber falhou: ${ids} != ${expect}`);
  const xml = global.AknExport.toXml(doc);
  fs.writeFileSync(path.join(OUT, 'dec-lei-with-insertions.akn.xml'), xml);
  console.log(`  OK   dec-lei-with-insertions.akn.xml  (${xml.length} bytes; insertArticleAt+renumber → ${ids})`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL dec-lei-with-insertions: ${e.message}`);
  n_fail++;
}

// 4. Test cross-references resolved (internal + external PT + UE)
try {
  const doc = global.newDocument('dec-lei');
  doc.number = '600'; doc.year = 2026;
  doc.subtype = 'dec-lei-transposicao';
  doc.shortTitle = 'Diploma com referências cruzadas (internas e externas).';
  doc.adoptionDate = '2026-06-01'; doc.publicationDate = '2026-06-05';
  doc.docDate = '2026-06-05'; doc.docDateText = '5 de junho';
  doc.body.items[0].heading = 'Objeto';
  doc.body.items[0].paragraphs[0].content =
    'O presente decreto-lei transpõe a Diretiva (UE) 2019/1937 do Parlamento Europeu, ' +
    'alterando o Decreto-Lei n.º 21/2023, de 27 de março.';
  doc.body.items[1].heading = 'Remissões internas';
  // Referência ao artigo 1.º DO PRÓPRIO diploma (existe → resolve para #art_1)
  doc.body.items[1].paragraphs[0].content =
    'Aplica-se o disposto no artigo 1.º para todos os efeitos.';
  doc.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  const xml = global.AknExport.toXml(doc);
  // Validar manualmente: deve conter pelo menos uma <ref ...> resolvida
  if (!xml.includes('<ref href="')) throw new Error('Nenhuma ref resolvida no XML.');
  if (!xml.includes('data.europa.eu/eli/dir/2019/1937')) throw new Error('Diretiva UE não resolvida.');
  if (!xml.includes('eli.gov.pt/eli/pt/dec-lei/2023/21')) throw new Error('DL externo não resolvido.');
  if (!xml.includes('href="#art_1"')) throw new Error('Ref interna ao art_1 não resolvida.');
  fs.writeFileSync(path.join(OUT, 'dec-lei-with-refs.akn.xml'), xml);
  console.log(`  OK   dec-lei-with-refs.akn.xml  (${xml.length} bytes; refs internas+PT+UE resolvidas)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL dec-lei-with-refs: ${e.message}`);
  n_fail++;
}

// 5. Test amendment mode (alterador + consolidated)
try {
  // Diploma alvo
  const target = global.newDocument('dec-lei');
  target.number = '21'; target.year = 2023;
  target.shortTitle = 'Diploma alvo (alvo de alteração).';
  target.adoptionDate = '2023-03-23'; target.publicationDate = '2023-03-27';
  target.docDate = '2023-03-27'; target.docDateText = '27 de março';
  target.body.items[0].heading = 'Objeto';
  target.body.items[0].paragraphs[0].content = 'O presente diploma estabelece X.';
  target.body.items[1].heading = 'Definições';
  target.body.items[1].paragraphs[0].content = 'Para efeitos do presente diploma entende-se por…';
  target.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2023-03-23' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2023-03-25' },
  ];
  // Construir alterador a partir do alvo
  const amender = global.Amendment.fromTarget(target);
  amender.number = '99'; amender.year = 2026;
  amender.adoptionDate = '2026-06-01'; amender.publicationDate = '2026-06-05';
  amender.docDate = '2026-06-05'; amender.docDateText = '5 de junho';
  amender.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  // Substitui art_2
  const newArt2 = JSON.parse(JSON.stringify(target.body.items[1]));
  newArt2.heading = 'Definições (nova redacção)';
  newArt2.paragraphs[0].content = 'Para efeitos do presente diploma considera-se…';
  global.Amendment.addReplace(amender, 'art_2', newArt2);
  // Revoga art_3
  global.Amendment.addRevoke(amender, 'art_3');

  // Export XML alterador
  const xmlAm = global.Amendment.toAknXml(amender);
  if (!xmlAm.includes('quotedStructure')) throw new Error('Falta <quotedStructure> no alterador.');
  fs.writeFileSync(path.join(OUT, 'amender.akn.xml'), xmlAm);
  console.log(`  OK   amender.akn.xml  (${xmlAm.length} bytes; alterador com <quotedStructure>)`);

  // Versão consolidada
  const consolidated = global.Amendment.applyAll(amender);
  const xmlCons = global.AknExport.toXml(consolidated);
  if (!xmlCons.includes('Definições (nova redacção)')) throw new Error('Consolidação não aplicou substituição.');
  fs.writeFileSync(path.join(OUT, 'consolidated.akn.xml'), xmlCons);
  console.log(`  OK   consolidated.akn.xml  (${xmlCons.length} bytes; alvo com alterações aplicadas)`);
  n_ok += 2;
} catch (e) {
  console.log(`  FAIL amendment: ${e.message}`);
  n_fail++;
}

// 6. Test Bluebell-PT roundtrip (serialize → parse → serialize, deve ser estável)
try {
  const doc = global.newDocument('dec-lei');
  doc.number = '700'; doc.year = 2026;
  doc.shortTitle = 'Diploma teste de roundtrip Bluebell-PT.';
  doc.adoptionDate = '2026-06-01'; doc.publicationDate = '2026-06-05';
  doc.docDate = '2026-06-05'; doc.docDateText = '5 de junho';
  doc.body.items[0].heading = 'Objeto';
  doc.body.items[0].paragraphs[0].content = 'O presente diploma regula X, Y e Z.';
  doc.body.items[1].heading = 'Definições';
  doc.body.items[1].paragraphs[0].num = '1 -';
  doc.body.items[1].paragraphs[0].content = 'Para efeitos do presente diploma:';
  doc.body.items[1].paragraphs[0].subPoints = [
    { id: 'art_2__para_1__lit_a', num: 'a)', content: 'Primeira alínea', subPoints: [] },
    { id: 'art_2__para_1__lit_b', num: 'b)', content: 'Segunda alínea', subPoints: [
      { id: 'art_2__para_1__lit_b__sublit_i', num: 'i)', content: 'Subalínea um' },
      { id: 'art_2__para_1__lit_b__sublit_ii', num: 'ii)', content: 'Subalínea dois' },
    ]},
  ];
  doc.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  const text1 = global.BluebellPt.serialize(doc);
  const doc2 = global.BluebellPt.parseToDoc(text1, doc);
  const text2 = global.BluebellPt.serialize(doc2);
  if (text1.replace(/\s+/g,' ').trim() !== text2.replace(/\s+/g,' ').trim()) {
    throw new Error('Bluebell roundtrip não estável');
  }
  // E exporta XML válido
  const xml = global.AknExport.toXml(doc2);
  fs.writeFileSync(path.join(OUT, 'bluebell-roundtrip.akn.xml'), xml);
  fs.writeFileSync(path.join(OUT, 'bluebell-roundtrip.bb.txt'), text1);
  console.log(`  OK   bluebell-roundtrip.akn.xml  (${xml.length} bytes; +${text1.length} chars Bluebell)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL bluebell-roundtrip: ${e.message}`);
  n_fail++;
}

// 7. Test LoDA inline → amender XML (edição word-level)
try {
  const target = global.newDocument('dec-lei');
  target.number = '21'; target.year = 2023;
  target.shortTitle = 'Diploma alvo da edição inline.';
  target.adoptionDate = '2023-03-23'; target.publicationDate = '2023-03-27';
  target.docDate = '2023-03-27'; target.docDateText = '27 de março';
  target.body.items[0].heading = 'Objeto';
  target.body.items[0].paragraphs[0].content = 'O presente diploma estabelece o regime A.';
  target.body.items[1].heading = 'Definições';
  target.body.items[1].paragraphs[0].content = 'Para efeitos do presente diploma…';
  target.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2023-03-23' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2023-03-25' },
  ];
  const amender = global.Amendment.fromTarget(target);
  amender.number = '50'; amender.year = 2026;
  amender.adoptionDate = '2026-06-01'; amender.publicationDate = '2026-06-05';
  amender.docDate = '2026-06-05'; amender.docDateText = '5 de junho';
  amender.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  // Editar inline: trocar "regime A" por "regime B (revisto)"
  global.LodaInline.editParagraph(amender, 'art_1__para_1',
    'O presente diploma estabelece o regime B (revisto).');
  const edits = global.LodaInline.listEdits(amender);
  if (edits.length !== 1) throw new Error(`esperava 1 edit, vi ${edits.length}`);
  if (!edits[0].tokens.some(t => t.op === '+')) throw new Error('tokens diff sem inserções');
  // Aplicar à lista de amendments e exportar
  global.LodaInline.applyToAmendmentList(amender);
  const xml = global.Amendment.toAknXml(amender);
  if (!xml.includes('regime B (revisto)')) throw new Error('edição inline não chegou ao XML');
  fs.writeFileSync(path.join(OUT, 'loda-inline.akn.xml'), xml);
  console.log(`  OK   loda-inline.akn.xml  (${xml.length} bytes; ${global.LodaInline.summary(amender)})`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL loda-inline: ${e.message}`);
  n_fail++;
}

// 8. Test export with comments (<note class="review">)
try {
  const doc = global.newDocument('dec-lei');
  doc.number = '800'; doc.year = 2026;
  doc.shortTitle = 'Diploma com comentários exportados como <note>.';
  doc.adoptionDate = '2026-06-01'; doc.publicationDate = '2026-06-05';
  doc.docDate = '2026-06-05'; doc.docDateText = '5 de junho';
  doc.body.items[0].heading = 'Objeto';
  doc.body.items[0].paragraphs[0].content = 'Conteúdo do artigo 1.';
  doc.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  // Adicionar 2 comentários (1 ao art_1, 1 ao art_1__para_1)
  doc.comments = [
    { id: 'c1', eId: 'art_1', text: 'Verificar coerência com lei habilitante.', author: 'bvidal', date: '2026-05-19T10:00:00Z', resolved: false },
    { id: 'c2', eId: 'art_1__para_1', text: 'Reformular para frase activa.', author: 'rev', date: '2026-05-19T11:00:00Z', resolved: false },
  ];
  doc._exportWithComments = true;
  const xml = global.AknExport.toXml(doc);
  if (!xml.includes('<authorialNote')) throw new Error('comentário não exportado como <authorialNote>');
  fs.writeFileSync(path.join(OUT, 'with-comments.akn.xml'), xml);
  console.log(`  OK   with-comments.akn.xml  (${xml.length} bytes; ${doc.comments.length} <authorialNote> injectados)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL with-comments: ${e.message}`);
  n_fail++;
}

// 9. Test ImportParser on real DRE Portaria (fixture: port-205B-2025.txt)
try {
  const fixtureText = fs.readFileSync(path.join(ROOT, 'test-fixtures', 'port-205B-2025.txt'), 'utf8');
  const parsed = global.ImportParser.parse(fixtureText);

  const checks = [
    ['type=portaria', parsed.actType === 'portaria'],
    ['number=205-B', parsed.number === '205-B'],
    ['year=2025', parsed.year === 2025],
    ['docDate', parsed.docDate === '2025-04-30'],
    ['no shortTitle absorption', parsed.shortTitle.length < 250],
    ['2+ recitals', parsed.recitals.length >= 2],
    ['formula apanhada', parsed.formula && parsed.formula.length > 100],
    ['habilitante = DL 43-B/2024', parsed.habilitante.includes('43-B') && parsed.habilitante.includes('2024')],
    ['12 artigos', parsed.articles.length === 12],
    ['todas epígrafes', parsed.articles.every(a => a.heading && a.heading.length > 3)],
    ['2 ministros assinantes', parsed.signatures.filter(s => s.name).length === 2],
    ['nome Joaquim Miranda Sarmento', parsed.signatures.some(s => s.name.includes('Miranda Sarmento'))],
    ['nome António Leitão Amaro', parsed.signatures.some(s => s.name.includes('Leitão Amaro'))],
    ['título Ministro de Estado e das Finanças preservado',
      parsed.signatures.some(s => s.title && s.title.includes('Estado e das Finanças'))],
    ['eId específico ministro-estado-financas',
      parsed.signatures.some(s => s.as === 'ministro-estado-financas')],
    ['eId específico ministro-presidencia',
      parsed.signatures.some(s => s.as === 'ministro-presidencia')],
  ];
  const fails = checks.filter(([, ok]) => !ok);
  if (fails.length) {
    throw new Error('Falhas: ' + fails.map(f => f[0]).join(', '));
  }
  console.log(`  OK   ImportParser real Portaria  (${checks.length}/${checks.length} verificações)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL ImportParser real Portaria: ${e.message}`);
  n_fail++;
}

// 10. Test DRE mock suggest
try {
  const res = global.DreMock.suggest('21 2023');
  if (!res.length || !res[0].label.includes('21/2023')) {
    throw new Error(`DRE suggest sem match: ${JSON.stringify(res.slice(0,2))}`);
  }
  const res2 = global.DreMock.suggest('rgpd');
  if (!res2.some(r => r.label.toLowerCase().includes('rgpd'))) {
    throw new Error('DRE não encontrou RGPD');
  }
  console.log(`  OK   DRE-mock suggest (DL 21/2023 + RGPD via fuzzy)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL DRE-mock: ${e.message}`);
  n_fail++;
}

const total = cases.length + 10;
console.log(`\n${n_ok}/${total} files generated.`);
console.log(`Next: validate with akn-pt:`);
console.log(`  python -m akn_pt batch editor/.smoke-output`);
process.exit(n_fail ? 1 : 0);
