// AKN-PT Editor — smoke tests (run from project root with Node)
// Validates that the XML generated by the editor passes XSD + Schematron.
//
// Usage:
//   node editor/smoke-test.js
//   python -m akn_pt batch editor/.smoke-output
//
// EUPL-1.2
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname);
const OUT = path.join(ROOT, '.smoke-output');
fs.mkdirSync(OUT, { recursive: true });

function loadFile(rel) {
  const code = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  eval(`(function() { ${code};
    if (typeof newDocument !== 'undefined') global.newDocument = newDocument;
    if (typeof ACT_TYPES !== 'undefined') global.ACT_TYPES = ACT_TYPES;
    if (typeof FORMULAS !== 'undefined') global.FORMULAS = FORMULAS;
    if (typeof AknExport !== 'undefined') global.AknExport = AknExport;
    if (typeof ImportParser !== 'undefined') global.ImportParser = ImportParser;
    if (typeof References !== 'undefined') { global.References = References; globalThis.References = References; }
    if (typeof Amendment !== 'undefined') { global.Amendment = Amendment; globalThis.Amendment = Amendment; }
    if (typeof Preview !== 'undefined') { global.Preview = Preview; globalThis.Preview = Preview; }
    if (typeof Diff !== 'undefined') { global.Diff = Diff; globalThis.Diff = Diff; }
    if (typeof LodaInline !== 'undefined') { global.LodaInline = LodaInline; globalThis.LodaInline = LodaInline; }
    if (typeof BluebellPt !== 'undefined') { global.BluebellPt = BluebellPt; globalThis.BluebellPt = BluebellPt; }
    if (typeof DreMock !== 'undefined') { global.DreMock = DreMock; globalThis.DreMock = DreMock; }
    if (typeof Renumber !== 'undefined') { global.Renumber = Renumber; globalThis.Renumber = Renumber; }
    if (typeof Suggestions !== 'undefined') { global.Suggestions = Suggestions; globalThis.Suggestions = Suggestions; }
    // expor para todos os módulos (akn-export precisa de ler References no fecho global)
    if (typeof AknExport !== 'undefined') globalThis.AknExport = AknExport;
  })();`);
}
loadFile('js/templates.js');
loadFile('js/references.js');  // tem de carregar antes do akn-export para o xmlText resolver
loadFile('js/renumber.js');    // tem de carregar antes do state para o renumber cascading
loadFile('js/dre-mock.js');
loadFile('js/akn-export.js');
loadFile('js/preview.js');
loadFile('js/diff.js');
loadFile('js/amendment.js');
loadFile('js/loda-inline.js');
loadFile('js/suggestions.js');
loadFile('js/bluebell-pt.js');
loadFile('js/import-parser.js');

// State precisa de localStorage (shim) e ignora Editor.refresh (guard typeof).
const _mem = {};
global.localStorage = {
  getItem: (k) => _mem[k] || null,
  setItem: (k, v) => { _mem[k] = String(v); },
  removeItem: (k) => { delete _mem[k]; },
};
loadFile('js/state.js');
// expor State (definido via IIFE em state.js)
eval(fs.readFileSync(path.join(ROOT, 'js/state.js'), 'utf8') + '\nglobal.State = State;');
// Snapshots depende de State + localStorage (shim acima); exposto via window-like
eval(fs.readFileSync(path.join(ROOT, 'js/snapshots.js'), 'utf8') + '\nglobal.Snapshots = Snapshots;');

const cases = [
  {
    name: 'dec-lei-simple',
    setup(d) {
      d.number = '99'; d.year = 2026;
      d.shortTitle = 'Diploma de teste exportado pelo editor.';
      d.adoptionDate = '2026-03-10';
      d.publicationDate = '2026-03-15';
      d.docDate = '2026-03-15'; d.docDateText = '15 de marco';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'O presente DL estabelece o regime.';
      d.signatures = [
        { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-03-10' },
        { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-03-12' },
      ];
    },
    type: 'dec-lei',
  },
  {
    name: 'dec-lei-with-footprint',
    setup(d) {
      d.number = '300'; d.year = 2026;
      d.shortTitle = 'Diploma com pegada legislativa (pos 2026-07-27).';
      d.adoptionDate = '2026-08-01';
      d.publicationDate = '2026-08-15';
      d.docDate = '2026-08-15'; d.docDateText = '15 de agosto';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'O presente DL estabelece X.';
      d.signatures = [
        { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-08-01' },
        { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-08-10' },
      ];
      d.workflow = [
        { id: 'step_1', refersTo: 'iniciativa', date: '2026-05-01', source: 'governo', description: 'Iniciativa.', inputs: [] },
        { id: 'step_2', refersTo: 'consulta-publica', date: '2026-06-01', source: 'dapl', description: 'Consulta publica.',
          inputs: [{ id: 'input_1', date: '2026-06-15', source: 'org-cip', type: 'contributo-consulta-publica', description: 'CIP.' }],
        },
        { id: 'step_3', refersTo: 'aprovacao-cm', date: '2026-08-01', source: 'cm', description: 'CM.', inputs: [] },
        { id: 'step_4', refersTo: 'publicacao', date: '2026-08-15', source: 'dre', description: 'DR.', inputs: [] },
      ];
    },
    type: 'dec-lei',
  },
  {
    name: 'lei-simple',
    setup(d) {
      d.number = '15'; d.year = 2026;
      d.shortTitle = 'Lei de teste do editor AKN-PT.';
      d.adoptionDate = '2026-02-01';
      d.publicationDate = '2026-02-10';
      d.docDate = '2026-02-10'; d.docDateText = '10 de fevereiro';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'A presente lei estabelece o regime.';
      d.signatures = [
        { role: 'signature', as: 'presidente-ar', name: 'PAR', date: '2026-02-01' },
        { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-02-05' },
        { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-02-08' },
      ];
    },
    type: 'lei',
  },
  {
    name: 'portaria-simple',
    setup(d) {
      d.number = '100'; d.year = 2026;
      d.shortTitle = 'Portaria de teste — regulamento de modelo.';
      d.adoptionDate = '2026-05-01';
      d.publicationDate = '2026-05-05';
      d.docDate = '2026-05-05'; d.docDateText = '5 de maio';
      d.habilitante = 'https://eli.gov.pt/eli/pt/dec-lei/2025/1/pt';
      d.habilitanteLabel = 'Decreto-Lei n.o 1/2025, de 5 de novembro';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'A presente portaria aprova o modelo.';
      d.signatures = [{ role: 'signature', as: 'ministro', name: 'Ministro X', date: '2026-05-01' }];
    },
    type: 'portaria',
  },
  {
    name: 'rcm-simple',
    setup(d) {
      d.number = '50'; d.year = 2026;
      d.shortTitle = 'Aprova plano nacional X.';
      d.adoptionDate = '2026-04-10';
      d.publicationDate = '2026-04-15';
      d.docDate = '2026-04-15'; d.docDateText = '15 de abril';
      d.body.items[0].content = 'Aprovar o Plano Nacional X.';
      d.signatures = [{ role: 'signature', as: 'primeiro-ministro', name: 'PM', date: '2026-04-10' }];
    },
    type: 'res-cm',
  },
  {
    name: 'dlr-acores',
    setup(d) {
      d.number = '5'; d.year = 2026;
      d.country = 'pt-20';
      d.shortTitle = 'Aprova regime regional X dos Acores.';
      d.adoptionDate = '2026-02-10';
      d.publicationDate = '2026-02-20';
      d.docDate = '2026-02-20'; d.docDateText = '20 de fevereiro';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'O presente DLR aprova o regime X.';
      d.signatures = [
        { role: 'signature', as: 'presidente-alra', name: 'PALRA', date: '2026-02-10' },
        { role: 'promulgation', as: 'representante-republica-acores', name: 'RR', date: '2026-02-15' },
      ];
    },
    type: 'dlr',
  },
  {
    // Tipo 5/9 — Decreto da Assembleia da República (tratado / convenção).
    // Estrutura com articulado simples; assinaturas PAR + PR.
    name: 'decreto-ar-simple',
    setup(d) {
      d.number = '12'; d.year = 2026;
      d.subtype = 'decreto-ar-tratado';
      d.formula = 'A Assembleia da República resolve, nos termos do n.º 5 do artigo 166.º da Constituição, aprovar a Convenção sobre cooperação X.';
      d.shortTitle = 'Aprova a Convenção sobre cooperação X assinada em Lisboa.';
      d.adoptionDate = '2026-03-15';
      d.publicationDate = '2026-03-22';
      d.docDate = '2026-03-22'; d.docDateText = '22 de marco';
      d.body.items[0].heading = 'Aprovação';
      d.body.items[0].paragraphs[0].content = 'E aprovada a Convenção sobre cooperação X, cujo texto se publica em anexo.';
      d.signatures = [
        { role: 'signature', as: 'presidente-ar', name: 'PAR', date: '2026-03-15' },
        { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-03-20' },
      ];
    },
    type: 'decreto-ar',
  },
  {
    // Tipo 7/9 — Despacho normativo ministerial com habilitante.
    // Estrutura semelhante a portaria.
    name: 'despacho-simple',
    setup(d) {
      d.number = '8'; d.year = 2026;
      d.shortTitle = 'Estabelece o regime de funcionamento da plataforma Y.';
      d.adoptionDate = '2026-04-10';
      d.publicationDate = '2026-04-15';
      d.docDate = '2026-04-15'; d.docDateText = '15 de abril';
      d.habilitante = 'https://eli.gov.pt/eli/pt/dec-lei/2025/45/pt';
      d.habilitanteLabel = 'Decreto-Lei n.o 45/2025, de 18 de junho';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'O presente despacho estabelece o regime de funcionamento da plataforma Y.';
      d.signatures = [
        { role: 'signature', as: 'ministro', name: 'Ministra da Administracao Interna', date: '2026-04-10' },
      ];
    },
    type: 'despacho-normativo',
  },
  {
    // Tipo 9/9 — Decreto Regulamentar Regional dos Açores com habilitante.
    name: 'drr-acores-simple',
    setup(d) {
      d.number = '3'; d.year = 2026;
      d.country = 'pt-20';
      d.shortTitle = 'Regulamenta o regime do procedimento X na Regiao Autonoma dos Acores.';
      d.adoptionDate = '2026-05-01';
      d.publicationDate = '2026-05-08';
      d.docDate = '2026-05-08'; d.docDateText = '8 de maio';
      d.habilitante = 'https://eli.gov.pt/eli/pt/dlr/2025/12/pt';
      d.habilitanteLabel = 'Decreto Legislativo Regional n.o 12/2025/A, de 10 de outubro';
      d.body.items[0].heading = 'Objeto';
      d.body.items[0].paragraphs[0].content = 'O presente DRR regulamenta o regime do procedimento X.';
      d.signatures = [
        { role: 'signature', as: 'presidente-governo-regional-acores', name: 'PGRA', date: '2026-05-01' },
      ];
    },
    type: 'drr',
  },
];

let n_ok = 0, n_fail = 0;
console.log(`Generating ${cases.length} test files (templates) + 1 imported in ${OUT}/\n`);

// 1. Tests from rich templates with user overrides
for (const c of cases) {
  try {
    const doc = global.newDocument(c.type);
    c.setup(doc);
    const xml = global.AknExport.toXml(doc);
    const file = path.join(OUT, `${c.name}.akn.xml`);
    fs.writeFileSync(file, xml);
    console.log(`  OK   ${c.name}.akn.xml  (${xml.length} bytes)`);
    n_ok++;
  } catch (e) {
    console.log(`  FAIL ${c.name}: ${e.message}`);
    n_fail++;
  }
}

// 1bis. DL with subalineas (i, ii, iii) nested under an alinea — exercita point recursivo
try {
  const doc = global.newDocument('dec-lei');
  doc.number = '101'; doc.year = 2026;
  doc.shortTitle = 'Diploma de teste com subalineas.';
  doc.adoptionDate = '2026-03-01'; doc.publicationDate = '2026-03-05';
  doc.docDate = '2026-03-05'; doc.docDateText = '5 de marco';
  // Replace article 2 (Definições) paragraphs with one that has nested subalineas
  doc.body.items[1].paragraphs[0].subPoints = [
    { id: 'art_2__para_1__lit_a', num: 'a)', content: 'Item primeiro;', subPoints: [] },
    { id: 'art_2__para_1__lit_b', num: 'b)', content: 'Item segundo, designadamente:', subPoints: [
      { id: 'art_2__para_1__lit_b__sublit_i', num: 'i)', content: 'sub-item 1;' },
      { id: 'art_2__para_1__lit_b__sublit_ii', num: 'ii)', content: 'sub-item 2;' },
      { id: 'art_2__para_1__lit_b__sublit_iii', num: 'iii)', content: 'sub-item 3.' },
    ]},
    { id: 'art_2__para_1__lit_c', num: 'c)', content: 'Item terceiro.', subPoints: [] },
  ];
  doc.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-03-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-03-03' },
  ];
  const xml = global.AknExport.toXml(doc);
  fs.writeFileSync(path.join(OUT, 'dec-lei-with-subalineas.akn.xml'), xml);
  console.log(`  OK   dec-lei-with-subalineas.akn.xml  (${xml.length} bytes; <point> com <list> aninhada)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL dec-lei-with-subalineas: ${e.message}`);
  n_fail++;
}

// 2. Import test: parse unmarked Portaria text and export
const portariaText = `Portaria n.º 249/2021
de 22 de novembro
Regulamenta o regime de apoio extraordinario as micro e pequenas empresas afetadas pela crise energetica.

O Decreto-Lei n.º 56/2021, de 30 de junho, estabeleceu o regime juridico de apoios extraordinarios.

Importa, por isso, fixar as condicoes de acesso.

Manda o Governo, pelo Ministro da Economia, ao abrigo do disposto no n.º 3 do artigo 8.º do Decreto-Lei n.º 56/2021, de 30 de junho, o seguinte:

Artigo 1.º
Objeto
A presente portaria regulamenta o regime.

Artigo 2.º
Beneficiarios
1 - Podem aceder ao apoio as empresas que cumulativamente:
a) Sejam micro ou pequenas empresas;
b) Demonstrem quebra de margem superior a 25%;
c) Tenham a situacao tributaria regularizada.

Artigo 3.º
Entrada em vigor
A presente portaria entra em vigor no dia seguinte ao da sua publicacao.`;

try {
  const parsed = global.ImportParser.parse(portariaText);
  const doc = global.ImportParser.toDocState(parsed);
  const xml = global.AknExport.toXml(doc);
  const file = path.join(OUT, 'imported-portaria.akn.xml');
  fs.writeFileSync(file, xml);
  console.log(`  OK   imported-portaria.akn.xml  (${xml.length} bytes; parser → exporter)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL imported-portaria: ${e.message}`);
  n_fail++;
}

// 3. Test inserting articles at arbitrary positions (insert/move feature)
try {
  // Usa o State real (com localStorage shim) para exercer insertArticleAt + renumberArticles.
  const doc = global.newDocument('dec-lei');
  doc.number = '500'; doc.year = 2026;
  doc.shortTitle = 'Exemplo de articulado com insercoes e renumeracao.';
  doc.adoptionDate = '2026-06-01'; doc.publicationDate = '2026-06-05';
  doc.docDate = '2026-06-05'; doc.docDateText = '5 de junho';
  doc.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  global.State.init(doc);
  // Inserir artigo entre art_2 e art_3 → renumera todos, novo fica art_3.
  global.State.insertArticleAt(doc.body.items[1].id);
  const newArt = doc.body.items[2];
  global.State.updateArticle(newArt.id, { heading: 'Disposicao Inserida' });
  global.State.updateParagraph(newArt.paragraphs[0].id, newArt.id, { content: 'Conteudo inserido por renumeracao.' });
  const ids = doc.body.items.map(a => a.id).join(',');
  const expect = ['art_1','art_2','art_3','art_4','art_5'].join(',');
  if (ids !== expect) throw new Error(`renumber falhou: ${ids} != ${expect}`);
  const xml = global.AknExport.toXml(doc);
  fs.writeFileSync(path.join(OUT, 'dec-lei-with-insertions.akn.xml'), xml);
  console.log(`  OK   dec-lei-with-insertions.akn.xml  (${xml.length} bytes; insertArticleAt+renumber → ${ids})`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL dec-lei-with-insertions: ${e.message}`);
  n_fail++;
}

// 4. Test cross-references resolved (internal + external PT + UE)
try {
  const doc = global.newDocument('dec-lei');
  doc.number = '600'; doc.year = 2026;
  doc.subtype = 'dec-lei-transposicao';
  doc.shortTitle = 'Diploma com referências cruzadas (internas e externas).';
  doc.adoptionDate = '2026-06-01'; doc.publicationDate = '2026-06-05';
  doc.docDate = '2026-06-05'; doc.docDateText = '5 de junho';
  doc.body.items[0].heading = 'Objeto';
  doc.body.items[0].paragraphs[0].content =
    'O presente decreto-lei transpõe a Diretiva (UE) 2019/1937 do Parlamento Europeu, ' +
    'alterando o Decreto-Lei n.º 21/2023, de 27 de março.';
  doc.body.items[1].heading = 'Remissões internas';
  // Referência ao artigo 1.º DO PRÓPRIO diploma (existe → resolve para #art_1)
  doc.body.items[1].paragraphs[0].content =
    'Aplica-se o disposto no artigo 1.º para todos os efeitos.';
  doc.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  const xml = global.AknExport.toXml(doc);
  // Validar manualmente: deve conter pelo menos uma <ref ...> resolvida
  if (!xml.includes('<ref href="')) throw new Error('Nenhuma ref resolvida no XML.');
  if (!xml.includes('data.europa.eu/eli/dir/2019/1937')) throw new Error('Diretiva UE não resolvida.');
  if (!xml.includes('eli.gov.pt/eli/pt/dec-lei/2023/21')) throw new Error('DL externo não resolvido.');
  if (!xml.includes('href="#art_1"')) throw new Error('Ref interna ao art_1 não resolvida.');
  fs.writeFileSync(path.join(OUT, 'dec-lei-with-refs.akn.xml'), xml);
  console.log(`  OK   dec-lei-with-refs.akn.xml  (${xml.length} bytes; refs internas+PT+UE resolvidas)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL dec-lei-with-refs: ${e.message}`);
  n_fail++;
}

// 5. Test amendment mode (alterador + consolidated)
try {
  // Diploma alvo
  const target = global.newDocument('dec-lei');
  target.number = '21'; target.year = 2023;
  target.shortTitle = 'Diploma alvo (alvo de alteração).';
  target.adoptionDate = '2023-03-23'; target.publicationDate = '2023-03-27';
  target.docDate = '2023-03-27'; target.docDateText = '27 de março';
  target.body.items[0].heading = 'Objeto';
  target.body.items[0].paragraphs[0].content = 'O presente diploma estabelece X.';
  target.body.items[1].heading = 'Definições';
  target.body.items[1].paragraphs[0].content = 'Para efeitos do presente diploma entende-se por…';
  target.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2023-03-23' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2023-03-25' },
  ];
  // Construir alterador a partir do alvo
  const amender = global.Amendment.fromTarget(target);
  amender.number = '99'; amender.year = 2026;
  amender.adoptionDate = '2026-06-01'; amender.publicationDate = '2026-06-05';
  amender.docDate = '2026-06-05'; amender.docDateText = '5 de junho';
  amender.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  // Substitui art_2
  const newArt2 = JSON.parse(JSON.stringify(target.body.items[1]));
  newArt2.heading = 'Definições (nova redacção)';
  newArt2.paragraphs[0].content = 'Para efeitos do presente diploma considera-se…';
  global.Amendment.addReplace(amender, 'art_2', newArt2);
  // Revoga art_3
  global.Amendment.addRevoke(amender, 'art_3');

  // Export XML alterador
  const xmlAm = global.Amendment.toAknXml(amender);
  if (!xmlAm.includes('quotedStructure')) throw new Error('Falta <quotedStructure> no alterador.');
  fs.writeFileSync(path.join(OUT, 'amender.akn.xml'), xmlAm);
  console.log(`  OK   amender.akn.xml  (${xmlAm.length} bytes; alterador com <quotedStructure>)`);

  // Versão consolidada
  const consolidated = global.Amendment.applyAll(amender);
  const xmlCons = global.AknExport.toXml(consolidated);
  if (!xmlCons.includes('Definições (nova redacção)')) throw new Error('Consolidação não aplicou substituição.');
  fs.writeFileSync(path.join(OUT, 'consolidated.akn.xml'), xmlCons);
  console.log(`  OK   consolidated.akn.xml  (${xmlCons.length} bytes; alvo com alterações aplicadas)`);
  n_ok += 2;
} catch (e) {
  console.log(`  FAIL amendment: ${e.message}`);
  n_fail++;
}

// 5bis. Test amendment temporal dimension + surgical ops
try {
  function buildTarget() {
    const target = global.newDocument('dec-lei');
    target.number = '21'; target.year = 2023;
    target.shortTitle = 'Diploma alvo (testes temporais + cirúrgicos).';
    target.adoptionDate = '2023-03-23'; target.publicationDate = '2023-03-27';
    target.docDate = '2023-03-27'; target.docDateText = '27 de março';
    target.body.items[0].heading = 'Objeto';
    target.body.items[0].paragraphs[0].content = 'O presente diploma estabelece X.';
    target.body.items[1].heading = 'Definições';
    target.body.items[1].paragraphs[0].num = '1 -';
    target.body.items[1].paragraphs[0].content = 'Para efeitos do presente diploma:';
    target.body.items[1].paragraphs[0].subPoints = [
      { id: 'art_2__para_1__lit_a', num: 'a)', content: 'Definição A original;', subPoints: [] },
      { id: 'art_2__para_1__lit_b', num: 'b)', content: 'Definição B original;', subPoints: [] },
      { id: 'art_2__para_1__lit_c', num: 'c)', content: 'Definição C original.', subPoints: [] },
    ];
    return target;
  }

  function assert(cond, msg) { if (!cond) throw new Error(msg); }

  // (a) applyAtDate antes da data → alteração NÃO aplica
  {
    const amender = global.Amendment.fromTarget(buildTarget());
    const newArt2 = JSON.parse(JSON.stringify(amender.target.state.body.items[1]));
    newArt2.heading = 'Definições (revistas em 2025)';
    global.Amendment.addReplace(amender, 'art_2', newArt2, '2025-01-01');

    const before = global.Amendment.applyAtDate(amender, '2024-12-31');
    assert(before.body.items[1].heading === 'Definições',
      `(a) antes da data devia manter heading original; vi "${before.body.items[1].heading}"`);
    assert(before._consolidatedAt === '2024-12-31', '(a) _consolidatedAt não foi marcado');
  }

  // (b) applyAtDate exactamente na data → APLICA
  {
    const amender = global.Amendment.fromTarget(buildTarget());
    const newArt2 = JSON.parse(JSON.stringify(amender.target.state.body.items[1]));
    newArt2.heading = 'Definições (revistas em 2025)';
    global.Amendment.addReplace(amender, 'art_2', newArt2, '2025-01-01');

    const onDate = global.Amendment.applyAtDate(amender, '2025-01-01');
    assert(onDate.body.items[1].heading === 'Definições (revistas em 2025)',
      `(b) na data devia aplicar; vi "${onDate.body.items[1].heading}"`);
  }

  // (c) replace-paragraph actualiza só o parágrafo
  {
    const target = buildTarget();
    // Garantir que art_1 tem >1 parágrafo para verificar isolamento
    target.body.items[0].paragraphs.push({
      id: 'art_1__para_2', num: '2 -',
      content: 'Segundo número do objeto, INTOCADO.', subPoints: [],
    });
    const amender = global.Amendment.fromTarget(target);
    const newPara = {
      id: 'IGNORADO_PELO_APPLY', num: '1 -',
      content: 'Novo conteúdo cirúrgico do n.º 1.',
      subPoints: [],
    };
    global.Amendment.addReplaceParagraph(amender, 'art_1', 'art_1__para_1', newPara);

    const out = global.Amendment.applyAll(amender);
    const art1 = out.body.items[0];
    assert(art1.paragraphs[0].id === 'art_1__para_1',
      '(c) id original do parágrafo deve ser preservado');
    assert(art1.paragraphs[0].content === 'Novo conteúdo cirúrgico do n.º 1.',
      `(c) parágrafo alvo não foi substituído; vi "${art1.paragraphs[0].content}"`);
    assert(art1.paragraphs[1].content === 'Segundo número do objeto, INTOCADO.',
      '(c) parágrafo vizinho foi inadvertidamente afectado');
  }

  // (d) replace-subpoint actualiza só a alínea alvo
  {
    const amender = global.Amendment.fromTarget(buildTarget());
    const newSp = {
      id: 'IGNORADO', num: 'b)',
      content: 'Definição B REVISTA;',
      subPoints: [],
    };
    global.Amendment.addReplaceSubPoint(
      amender, 'art_2', 'art_2__para_1', 'art_2__para_1__lit_b', newSp,
    );

    const out = global.Amendment.applyAll(amender);
    const sps = out.body.items[1].paragraphs[0].subPoints;
    assert(sps.length === 3, `(d) número de alíneas deve manter-se em 3; vi ${sps.length}`);
    assert(sps[0].content === 'Definição A original;', '(d) alínea a) foi afectada');
    assert(sps[1].id === 'art_2__para_1__lit_b', '(d) id original da alínea b) deve manter-se');
    assert(sps[1].content === 'Definição B REVISTA;', `(d) alínea b) não foi substituída; vi "${sps[1].content}"`);
    assert(sps[2].content === 'Definição C original.', '(d) alínea c) foi afectada');
  }

  // (e) applyAll ≡ aplicar tudo (sentinela 9999) — duas alterações datadas + uma sem data
  {
    const amender = global.Amendment.fromTarget(buildTarget());
    const newArt2_2024 = JSON.parse(JSON.stringify(amender.target.state.body.items[1]));
    newArt2_2024.heading = 'Definições v2024';
    global.Amendment.addReplace(amender, 'art_2', newArt2_2024, '2024-06-01');

    const newArt2_2026 = JSON.parse(JSON.stringify(amender.target.state.body.items[1]));
    newArt2_2026.heading = 'Definições v2026';
    global.Amendment.addReplace(amender, 'art_2', newArt2_2026, '2026-01-15');

    global.Amendment.addRevoke(amender, 'art_3');  // sem data → entra sempre

    const out = global.Amendment.applyAll(amender);
    // A última a aplicar (data mais alta) ganha — v2026
    assert(out.body.items[1].heading === 'Definições v2026',
      `(e) applyAll devia terminar em v2026; vi "${out.body.items[1].heading}"`);
    // E o revoke (sem data) também deve estar aplicado
    assert(!out.body.items.some(a => a.id === 'art_3'),
      '(e) revoke sem data não foi aplicado em applyAll');

    // Cross-check intermédio: em 2024-06-01 devia ver v2024
    const mid = global.Amendment.applyAtDate(amender, '2024-06-01');
    assert(mid.body.items[1].heading === 'Definições v2024',
      `(e) em 2024-06-01 devia ver v2024; vi "${mid.body.items[1].heading}"`);
    // E o revoke sem data também aplica aí
    assert(!mid.body.items.some(a => a.id === 'art_3'),
      '(e) revoke sem data não foi aplicado em applyAtDate');
  }

  // (f) timeline devolve datas distintas ordenadas (excluindo null)
  {
    const amender = global.Amendment.fromTarget(buildTarget());
    const dummy = JSON.parse(JSON.stringify(amender.target.state.body.items[1]));
    global.Amendment.addReplace(amender, 'art_2', dummy, '2026-01-15');
    global.Amendment.addReplace(amender, 'art_2', dummy, '2024-06-01');
    global.Amendment.addReplace(amender, 'art_2', dummy, '2024-06-01'); // duplicada
    global.Amendment.addRevoke(amender, 'art_3'); // sem data → excluída

    const tl = global.Amendment.timeline(amender);
    const expected = ['2024-06-01', '2026-01-15'];
    assert(JSON.stringify(tl) === JSON.stringify(expected),
      `(f) timeline esperada ${JSON.stringify(expected)}; vi ${JSON.stringify(tl)}`);
  }

  // (g) backward compat: addReplace sem effectiveDate → effectiveDate null
  {
    const amender = global.Amendment.fromTarget(buildTarget());
    const dummy = JSON.parse(JSON.stringify(amender.target.state.body.items[1]));
    global.Amendment.addReplace(amender, 'art_2', dummy);
    assert(amender.amendments[0].effectiveDate === null,
      `(g) addReplace sem data devia produzir effectiveDate null; vi ${amender.amendments[0].effectiveDate}`);
  }

  console.log(`  OK   amendment-temporal+surgical  (7 sub-testes: a,b,c,d,e,f,g)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL amendment-temporal+surgical: ${e.message}`);
  n_fail++;
}

// 6. Test Bluebell-PT roundtrip (serialize → parse → serialize, deve ser estável)
try {
  const doc = global.newDocument('dec-lei');
  doc.number = '700'; doc.year = 2026;
  doc.shortTitle = 'Diploma teste de roundtrip Bluebell-PT.';
  doc.adoptionDate = '2026-06-01'; doc.publicationDate = '2026-06-05';
  doc.docDate = '2026-06-05'; doc.docDateText = '5 de junho';
  doc.body.items[0].heading = 'Objeto';
  doc.body.items[0].paragraphs[0].content = 'O presente diploma regula X, Y e Z.';
  doc.body.items[1].heading = 'Definições';
  doc.body.items[1].paragraphs[0].num = '1 -';
  doc.body.items[1].paragraphs[0].content = 'Para efeitos do presente diploma:';
  doc.body.items[1].paragraphs[0].subPoints = [
    { id: 'art_2__para_1__lit_a', num: 'a)', content: 'Primeira alínea', subPoints: [] },
    { id: 'art_2__para_1__lit_b', num: 'b)', content: 'Segunda alínea', subPoints: [
      { id: 'art_2__para_1__lit_b__sublit_i', num: 'i)', content: 'Subalínea um' },
      { id: 'art_2__para_1__lit_b__sublit_ii', num: 'ii)', content: 'Subalínea dois' },
    ]},
  ];
  doc.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  const text1 = global.BluebellPt.serialize(doc);
  const doc2 = global.BluebellPt.parseToDoc(text1, doc);
  const text2 = global.BluebellPt.serialize(doc2);
  if (text1.replace(/\s+/g,' ').trim() !== text2.replace(/\s+/g,' ').trim()) {
    throw new Error('Bluebell roundtrip não estável');
  }
  // E exporta XML válido
  const xml = global.AknExport.toXml(doc2);
  fs.writeFileSync(path.join(OUT, 'bluebell-roundtrip.akn.xml'), xml);
  fs.writeFileSync(path.join(OUT, 'bluebell-roundtrip.bb.txt'), text1);
  console.log(`  OK   bluebell-roundtrip.akn.xml  (${xml.length} bytes; +${text1.length} chars Bluebell)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL bluebell-roundtrip: ${e.message}`);
  n_fail++;
}

// 7. Test LoDA inline → amender XML (edição word-level)
try {
  const target = global.newDocument('dec-lei');
  target.number = '21'; target.year = 2023;
  target.shortTitle = 'Diploma alvo da edição inline.';
  target.adoptionDate = '2023-03-23'; target.publicationDate = '2023-03-27';
  target.docDate = '2023-03-27'; target.docDateText = '27 de março';
  target.body.items[0].heading = 'Objeto';
  target.body.items[0].paragraphs[0].content = 'O presente diploma estabelece o regime A.';
  target.body.items[1].heading = 'Definições';
  target.body.items[1].paragraphs[0].content = 'Para efeitos do presente diploma…';
  target.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2023-03-23' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2023-03-25' },
  ];
  const amender = global.Amendment.fromTarget(target);
  amender.number = '50'; amender.year = 2026;
  amender.adoptionDate = '2026-06-01'; amender.publicationDate = '2026-06-05';
  amender.docDate = '2026-06-05'; amender.docDateText = '5 de junho';
  amender.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  // Editar inline: trocar "regime A" por "regime B (revisto)"
  global.LodaInline.editParagraph(amender, 'art_1__para_1',
    'O presente diploma estabelece o regime B (revisto).');
  const edits = global.LodaInline.listEdits(amender);
  if (edits.length !== 1) throw new Error(`esperava 1 edit, vi ${edits.length}`);
  if (!edits[0].tokens.some(t => t.op === '+')) throw new Error('tokens diff sem inserções');
  // Aplicar à lista de amendments e exportar
  global.LodaInline.applyToAmendmentList(amender);
  const xml = global.Amendment.toAknXml(amender);
  if (!xml.includes('regime B (revisto)')) throw new Error('edição inline não chegou ao XML');
  fs.writeFileSync(path.join(OUT, 'loda-inline.akn.xml'), xml);
  console.log(`  OK   loda-inline.akn.xml  (${xml.length} bytes; ${global.LodaInline.summary(amender)})`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL loda-inline: ${e.message}`);
  n_fail++;
}

// 8. Test export with comments (<note class="review">)
try {
  const doc = global.newDocument('dec-lei');
  doc.number = '800'; doc.year = 2026;
  doc.shortTitle = 'Diploma com comentários exportados como <note>.';
  doc.adoptionDate = '2026-06-01'; doc.publicationDate = '2026-06-05';
  doc.docDate = '2026-06-05'; doc.docDateText = '5 de junho';
  doc.body.items[0].heading = 'Objeto';
  doc.body.items[0].paragraphs[0].content = 'Conteúdo do artigo 1.';
  doc.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-06-01' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-06-03' },
  ];
  // Adicionar 2 comentários (1 ao art_1, 1 ao art_1__para_1)
  doc.comments = [
    { id: 'c1', eId: 'art_1', text: 'Verificar coerência com lei habilitante.', author: 'bvidal', date: '2026-05-19T10:00:00Z', resolved: false },
    { id: 'c2', eId: 'art_1__para_1', text: 'Reformular para frase activa.', author: 'rev', date: '2026-05-19T11:00:00Z', resolved: false },
  ];
  doc._exportWithComments = true;
  const xml = global.AknExport.toXml(doc);
  if (!xml.includes('<authorialNote')) throw new Error('comentário não exportado como <authorialNote>');
  fs.writeFileSync(path.join(OUT, 'with-comments.akn.xml'), xml);
  console.log(`  OK   with-comments.akn.xml  (${xml.length} bytes; ${doc.comments.length} <authorialNote> injectados)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL with-comments: ${e.message}`);
  n_fail++;
}

// 9. Test ImportParser on real DRE Portaria (fixture: port-205B-2025.txt)
try {
  const fixtureText = fs.readFileSync(path.join(ROOT, 'test-fixtures', 'port-205B-2025.txt'), 'utf8');
  const parsed = global.ImportParser.parse(fixtureText);

  const checks = [
    ['type=portaria', parsed.actType === 'portaria'],
    ['number=205-B', parsed.number === '205-B'],
    ['year=2025', parsed.year === 2025],
    ['docDate', parsed.docDate === '2025-04-30'],
    ['no shortTitle absorption', parsed.shortTitle.length < 250],
    ['2+ recitals', parsed.recitals.length >= 2],
    ['formula apanhada', parsed.formula && parsed.formula.length > 100],
    ['habilitante = DL 43-B/2024', parsed.habilitante.includes('43-B') && parsed.habilitante.includes('2024')],
    ['12 artigos', parsed.articles.length === 12],
    ['todas epígrafes', parsed.articles.every(a => a.heading && a.heading.length > 3)],
    ['2 ministros assinantes', parsed.signatures.filter(s => s.name).length === 2],
    ['nome Joaquim Miranda Sarmento', parsed.signatures.some(s => s.name.includes('Miranda Sarmento'))],
    ['nome António Leitão Amaro', parsed.signatures.some(s => s.name.includes('Leitão Amaro'))],
    ['título Ministro de Estado e das Finanças preservado',
      parsed.signatures.some(s => s.title && s.title.includes('Estado e das Finanças'))],
    ['eId específico ministro-estado-financas',
      parsed.signatures.some(s => s.as === 'ministro-estado-financas')],
    ['eId específico ministro-presidencia',
      parsed.signatures.some(s => s.as === 'ministro-presidencia')],
    ['sem eIds duplicados', (() => {
      const all = [];
      parsed.articles.forEach(a => {
        all.push(a.id);
        a.paragraphs.forEach(p => {
          all.push(p.id);
          (p.subPoints || []).forEach(sp => {
            all.push(sp.id);
            (sp.subPoints || []).forEach(ssp => all.push(ssp.id));
          });
        });
      });
      return all.length === new Set(all).size;
    })()],
    ['art_3 tem 5 parágrafos (intro + 4 numerados)', (() => {
      const a = parsed.articles.find(x => x.id === 'art_3');
      return a && a.paragraphs.length === 5
          && a.paragraphs[0].num === '' && a.paragraphs[1].num === '1 -';
    })()],
  ];
  const fails = checks.filter(([, ok]) => !ok);
  if (fails.length) {
    throw new Error('Falhas: ' + fails.map(f => f[0]).join(', '));
  }
  console.log(`  OK   ImportParser real Portaria  (${checks.length}/${checks.length} verificações)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL ImportParser real Portaria: ${e.message}`);
  n_fail++;
}

// 9bis. Test ImportParser signature detection — multi-line bloco assinaturas
//       (DL com PR + PM + 2 ministros em LINHAS SEPARADAS).
try {
  const dlText = `Decreto-Lei n.º 99/2026
de 15 de março
Estabelece o regime experimental do programa Y.

Considerando que importa fixar as condições.

Assim:
Nos termos da alínea a) do n.º 1 do artigo 198.º da Constituição, o Governo decreta o seguinte:

Artigo 1.º
Objeto
O presente decreto-lei estabelece o regime experimental do programa Y.

Artigo 2.º
Entrada em vigor
O presente diploma entra em vigor no dia seguinte ao da sua publicação.

Visto e aprovado em Conselho de Ministros de 10 de março de 2026.
O Primeiro-Ministro, Luís Montenegro.
O Ministro de Estado e das Finanças, Joaquim Miranda Sarmento.
O Ministro da Presidência, António Leitão Amaro.
Promulgado em 12 de março de 2026.
Publique-se.
O Presidente da República, Marcelo Rebelo de Sousa.
Referendado em 14 de março de 2026.
O Primeiro-Ministro, Luís Montenegro.`;
  const parsed = global.ImportParser.parse(dlText);
  const sigs = parsed.signatures;
  const checks = [
    ['type=dec-lei', parsed.actType === 'dec-lei'],
    ['PM capturado', sigs.some(s => s.as === 'primeiro-ministro' && s.name.includes('Montenegro'))],
    ['PR capturado', sigs.some(s => s.as === 'presidente-republica' && s.name.includes('Marcelo'))],
    ['Ministro Finanças', sigs.some(s => /finan/i.test(s.as) && s.name.includes('Miranda'))],
    ['Ministro Presidência', sigs.some(s => /presidencia/i.test(s.as) && s.name.includes('Leitão'))],
    ['promulgation role para PR', sigs.some(s => s.as === 'presidente-republica' && s.role === 'promulgation')],
  ];
  const fails = checks.filter(([, ok]) => !ok);
  if (fails.length) throw new Error('Falhas: ' + fails.map(f => f[0]).join(', ') + ' | sigs=' + JSON.stringify(sigs.map(s => ({as: s.as, name: s.name}))));
  console.log(`  OK   ImportParser DL multi-linha (${checks.length}/${checks.length}; PR+PM+2 ministros)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL ImportParser DL multi-linha: ${e.message}`);
  n_fail++;
}

// 9ter. Test ImportParser — Portaria com 3 ministros em LINHAS SEPARADAS.
try {
  const portText = `Portaria n.º 777/2026
de 5 de junho
Aprova o regulamento conjunto Z.

Manda o Governo, pelo Ministro de Estado e das Finanças, pela Ministra da Saúde e pelo Ministro da Educação, ao abrigo do disposto no artigo 8.º do Decreto-Lei n.º 1/2025, o seguinte:

Artigo 1.º
Objeto
A presente portaria aprova o regulamento Z.

Artigo 2.º
Entrada em vigor
A presente portaria entra em vigor no dia seguinte ao da sua publicação.

Em 1 de junho de 2026.
O Ministro de Estado e das Finanças, Joaquim Miranda Sarmento.
A Ministra da Saúde, Ana Paula Martins.
O Ministro da Educação, Fernando Alexandre.`;
  const parsed = global.ImportParser.parse(portText);
  const sigs = parsed.signatures;
  const checks = [
    ['type=portaria', parsed.actType === 'portaria'],
    ['3 ministros assinantes', sigs.filter(s => s.name && /^ministr/i.test(s.as)).length === 3],
    ['Finanças', sigs.some(s => /finan/i.test(s.as) && s.name.includes('Miranda'))],
    ['Saúde', sigs.some(s => /saude/i.test(s.as) && s.name.includes('Ana Paula'))],
    ['Educação', sigs.some(s => /educacao/i.test(s.as) && s.name.includes('Fernando'))],
  ];
  const fails = checks.filter(([, ok]) => !ok);
  if (fails.length) throw new Error('Falhas: ' + fails.map(f => f[0]).join(', ') + ' | sigs=' + JSON.stringify(sigs.map(s => ({as: s.as, name: s.name}))));
  console.log(`  OK   ImportParser Portaria 3 ministros multi-linha (${checks.length}/${checks.length})`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL ImportParser Portaria 3 ministros multi-linha: ${e.message}`);
  n_fail++;
}

// 9quater. Test ImportParser — "Promulgado em DD/MM/YYYY." numa linha e
//          "O Presidente da República, Nome." na linha seguinte.
try {
  const dlText = `Decreto-Lei n.º 50/2026
de 1 de fevereiro
Aprova X.

Assim:
Nos termos da alínea a) do n.º 1 do artigo 198.º da Constituição, o Governo decreta o seguinte:

Artigo 1.º
Objeto
O presente decreto-lei aprova X.

Visto e aprovado em Conselho de Ministros de 25 de janeiro de 2026.
O Primeiro-Ministro, Luís Montenegro.
Promulgado em 28 de janeiro de 2026.
O Presidente da República, Marcelo Rebelo de Sousa.`;
  const parsed = global.ImportParser.parse(dlText);
  const sigs = parsed.signatures;
  const pr = sigs.find(s => s.as === 'presidente-republica');
  if (!pr) throw new Error('PR não capturado | sigs=' + JSON.stringify(sigs.map(s => ({as: s.as, name: s.name}))));
  if (!pr.name || !pr.name.includes('Marcelo')) throw new Error('PR sem nome correcto: ' + JSON.stringify(pr));
  if (pr.role !== 'promulgation') throw new Error('PR role errado: ' + pr.role);
  console.log(`  OK   ImportParser PR via "Promulgado em…" + linha seguinte`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL ImportParser PR via Promulgado em: ${e.message}`);
  n_fail++;
}

// 10. Test DRE mock suggest
try {
  const res = global.DreMock.suggest('21 2023');
  if (!res.length || !res[0].label.includes('21/2023')) {
    throw new Error(`DRE suggest sem match: ${JSON.stringify(res.slice(0,2))}`);
  }
  const res2 = global.DreMock.suggest('rgpd');
  if (!res2.some(r => r.label.toLowerCase().includes('rgpd'))) {
    throw new Error('DRE não encontrou RGPD');
  }
  console.log(`  OK   DRE-mock suggest (DL 21/2023 + RGPD via fuzzy)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL DRE-mock: ${e.message}`);
  n_fail++;
}

// 10b. Test Renumber cascading — text refs + comments + amendments
try {
  // Reset localStorage entre testes para evitar contaminação
  Object.keys(_mem).forEach(k => delete _mem[k]);

  const doc = global.newDocument('dec-lei');
  doc.number = '700'; doc.year = 2026;
  doc.shortTitle = 'Diploma para testar renumber cascading.';
  global.State.init(doc);

  // Cria 3 artigos
  global.State.addArticle();  // art_2
  global.State.addArticle();  // art_3

  // Editar conteúdos para introduzir refs internas e externas
  const d = global.State.get();
  d.body.items[0].heading = 'Objeto';
  d.body.items[0].paragraphs[0].content = 'O regime previsto neste diploma aplica-se sem prejuízo do disposto no artigo 3.º.';
  d.body.items[1].heading = 'Definições';
  d.body.items[1].paragraphs[0].content = 'Para efeitos do artigo 1.º, entende-se por X o que vier a ser definido.';
  d.body.items[2].heading = 'Disposição final';
  d.body.items[2].paragraphs[0].content = 'O presente diploma entra em vigor 30 dias após a publicação. Não derroga o artigo 3.º do Código Civil.';

  d.comments = [
    { id: 'cA', eId: 'art_2', text: 'Rever definição.', author: 'rev', date: '2026-05-25T10:00:00Z', resolved: false },
    { id: 'cB', eId: 'art_3__para_1', text: 'Verificar prazo.', author: 'rev', date: '2026-05-25T10:01:00Z', resolved: false },
  ];

  // ---- Move 1: subir art_3 (Disposição final) para o meio (passa a art_2) ----
  global.State.moveArticleUp('art_3');
  let d2 = global.State.get();

  // Após o 1.º move:
  //   pos 0 = art_1 Objeto (não se moveu; ref "artigo 3.º" deve agora apontar "artigo 2.º")
  //   pos 1 = art_2 Disposição final (era art_3)
  //   pos 2 = art_3 Definições (era art_2)
  if (d2.body.items[1].heading !== 'Disposição final') throw new Error('(1) Disposição final não está em art_2');
  if (d2.body.items[2].heading !== 'Definições') throw new Error('(1) Definições não está em art_3');

  // (a) ref interna em Objeto: artigo 3 → artigo 2 (old_art_3 → new_art_2)
  if (!d2.body.items[0].paragraphs[0].content.includes('artigo 2.º')) {
    throw new Error('(a) Objeto deveria referir "artigo 2.º"; viu: ' + d2.body.items[0].paragraphs[0].content);
  }
  // (b) ref externa "artigo 3.º do Código Civil" em Disposição final: anti-FP, inalterada
  const dispNow = d2.body.items[1];
  if (!dispNow.paragraphs[0].content.includes('artigo 3.º do Código Civil')) {
    throw new Error('(b) ref CC foi indevidamente tocada; viu: ' + dispNow.paragraphs[0].content);
  }
  // (c) ref em Definições "artigo 1.º" — art_1 (Objeto) não se moveu → inalterada
  const defNow = d2.body.items[2];
  if (!defNow.paragraphs[0].content.includes('artigo 1.º')) {
    throw new Error('(c) Definições "artigo 1.º" devia manter-se; viu: ' + defNow.paragraphs[0].content);
  }
  // (d) Comments — cA (era art_2/Definições) deve apontar para art_3
  if (d2.comments.find(c => c.id === 'cA').eId !== 'art_3') {
    throw new Error('(d) cA esperava art_3, viu ' + d2.comments.find(c => c.id === 'cA').eId);
  }
  // (e) cB (era art_3__para_1/Disposição p1) → art_2__para_1
  if (d2.comments.find(c => c.id === 'cB').eId !== 'art_2__para_1') {
    throw new Error('(e) cB esperava art_2__para_1, viu ' + d2.comments.find(c => c.id === 'cB').eId);
  }

  // ---- Move 2: subir art_2 (Disposição final, recentemente renumerada) ao topo ----
  global.State.moveArticleUp('art_2');
  d2 = global.State.get();

  // Após o 2.º move:
  //   pos 0 = art_1 Disposição final
  //   pos 1 = art_2 Objeto (passou de art_1)
  //   pos 2 = art_3 Definições (não se moveu)
  if (d2.body.items[0].heading !== 'Disposição final') throw new Error('(2) Disposição final não está em art_1');
  if (d2.body.items[1].heading !== 'Objeto') throw new Error('(2) Objeto não está em art_2');

  // (f) Em Objeto, a ref que era "artigo 2.º" (do 1.º move) deve agora ser "artigo 1.º"
  //     porque a Disposição final (alvo da ref) passou de art_2 para art_1.
  if (!d2.body.items[1].paragraphs[0].content.includes('artigo 1.º')) {
    throw new Error('(f) Objeto deveria referir agora "artigo 1.º"; viu: ' + d2.body.items[1].paragraphs[0].content);
  }
  // (g) Em Definições, ref "artigo 1.º" → "artigo 2.º" (porque Objeto passou de art_1 para art_2)
  if (!d2.body.items[2].paragraphs[0].content.includes('artigo 2.º')) {
    throw new Error('(g) Definições deveria referir agora "artigo 2.º"; viu: ' + d2.body.items[2].paragraphs[0].content);
  }
  // (h) Comments — cA (estava em art_3 após 1.º move) → mantém art_3 (Definições não se moveu)
  if (d2.comments.find(c => c.id === 'cA').eId !== 'art_3') {
    throw new Error('(h) cA esperava art_3, viu ' + d2.comments.find(c => c.id === 'cA').eId);
  }
  // (i) cB (estava em art_2__para_1) → art_1__para_1
  if (d2.comments.find(c => c.id === 'cB').eId !== 'art_1__para_1') {
    throw new Error('(i) cB esperava art_1__para_1, viu ' + d2.comments.find(c => c.id === 'cB').eId);
  }

  // (j) Sumário (no doc) e undo (in-memory via State) expostos
  if (!d2._lastRenumberSummary) throw new Error('(j) sem sumário do renumber');
  if (!global.State.hasRenumberUndo()) throw new Error('(j) sem undo in-memory');
  const undo = global.State.consumeRenumberUndo();
  if (!undo || !Array.isArray(undo.body.items)) throw new Error('(j) undo mal formado');
  if (global.State.hasRenumberUndo()) throw new Error('(j) consume não limpou');

  // (k) XML do exporter contém refs reescritas
  const xml = global.AknExport.toXml(d2);
  if (!xml.includes('href="#art_1"') || !xml.includes('href="#art_2"')) {
    throw new Error('(k) XML sem refs reescritas; xml head: ' + xml.slice(0, 300));
  }

  console.log(`  OK   Renumber cascading (11 sub-testes: 2 moves + a-k)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL Renumber cascading: ${e.message}`);
  n_fail++;
}

// 10c. Test State.reorderArticles — base do drag-and-drop do mini-TOC
try {
  Object.keys(_mem).forEach(k => delete _mem[k]);
  const doc = global.newDocument('dec-lei');
  doc.number = '750'; doc.year = 2026;
  doc.shortTitle = 'Reorder test.';
  // Reset articulado para 4 artigos canónicos: A, B, C, D
  doc.body.items = ['A','B','C','D'].map((tag, i) => ({
    id: `art_${i+1}`, num: `Artigo ${i+1}.º`, heading: `Artigo ${tag}`,
    paragraphs: [{ id: `art_${i+1}__para_1`, num: '', content: `Conteúdo ${tag}.`, subPoints: [] }],
  }));
  doc.nextArticleNum = 5;
  global.State.init(doc);

  const d = global.State.get();

  // Reordenar: D, A, B, C (D vai para o início)
  global.State.reorderArticles(['art_4', 'art_1', 'art_2', 'art_3']);
  const d2 = global.State.get();
  const heads = d2.body.items.map(a => a.heading);
  // Após o reorder + renumber: pos 0 = D (com id art_1), pos 1 = A (art_2), …
  if (heads.join(',') !== 'Artigo D,Artigo A,Artigo B,Artigo C') {
    throw new Error('(a) ordem errada: ' + heads.join(','));
  }
  if (d2.body.items[0].id !== 'art_1') throw new Error('(a) eId não recolocado em pos 0');
  if (d2.body.items[3].id !== 'art_4') throw new Error('(a) eId não recolocado em pos 3');

  // Idempotente: chamar com a ordem actual não muta
  const snapBefore = JSON.stringify(d2.body.items.map(a => a.id));
  global.State.reorderArticles(['art_1', 'art_2', 'art_3', 'art_4']);
  const snapAfter = JSON.stringify(global.State.get().body.items.map(a => a.id));
  if (snapBefore !== snapAfter) throw new Error('(b) idempotente falhou');

  // Robusto a ids parciais: passar só ['art_3'] coloca art_3 em primeiro e
  // os restantes mantêm-se na ordem original a seguir.
  global.State.reorderArticles(['art_3']);
  const d3 = global.State.get();
  if (d3.body.items[0].heading !== 'Artigo B') {
    throw new Error('(c) reorder parcial falhou: ' + d3.body.items[0].heading);
  }

  console.log(`  OK   State.reorderArticles (3 sub-testes: a-c)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL State.reorderArticles: ${e.message}`);
  n_fail++;
}

// 10d. Test Suggestions — add / accept / reject / re-anchor / drift
try {
  Object.keys(_mem).forEach(k => delete _mem[k]);
  const doc = global.newDocument('dec-lei');
  doc.number = '888'; doc.year = 2026;
  doc.shortTitle = 'Suggestions test.';
  doc.body.items[0].id = 'art_1';
  doc.body.items[0].heading = 'Objeto';
  doc.body.items[0].paragraphs[0].id = 'art_1__para_1';
  doc.body.items[0].paragraphs[0].content = 'O presente diploma estabelece o regime experimental aplicável a todas as entidades públicas.';
  global.State.init(doc);
  const d = global.State.get();

  // (a) add — sugere "Refer um regime piloto" em vez de "estabelece o regime experimental"
  //     Texto: "O presente diploma estabelece o regime experimental aplicável..."
  //                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  //                                       start=21                          end=55
  const content = d.body.items[0].paragraphs[0].content;
  const start = content.indexOf('estabelece o regime experimental');
  const end = start + 'estabelece o regime experimental'.length;
  const s1 = global.Suggestions.add(d, 'art_1__para_1', 'content',
    { start, end }, 'estatui o regime-piloto', { author: 'rev' });
  if (s1.status !== 'pending') throw new Error('(a) status inicial não é pending');
  if (s1.originalText !== 'estabelece o regime experimental') throw new Error('(a) originalText mal capturado');
  if (global.Suggestions.count(d) !== 1) throw new Error('(a) count != 1');

  // (b) add — uma 2.ª sugestão que vem DEPOIS da 1.ª na ranges
  //     "entidades públicas" → "entidades do sector público"
  const start2 = content.indexOf('entidades públicas');
  const end2 = start2 + 'entidades públicas'.length;
  const s2 = global.Suggestions.add(d, 'art_1__para_1', 'content',
    { start: start2, end: end2 }, 'entidades do sector público', { author: 'rev' });

  // (c) accept s1 — content muda, s2 deve ter range shiftada (porque o aceite
  //     aconteceu antes do início da s2 e o delta é proposedText.len-original.len)
  global.Suggestions.accept(d, s1.id);
  if (s1.status !== 'accepted') throw new Error('(c) s1 não foi aceite');
  const newContent = d.body.items[0].paragraphs[0].content;
  if (!newContent.includes('estatui o regime-piloto')) {
    throw new Error('(c) content não foi patcheado: ' + newContent);
  }
  // s2 ainda pending mas a range foi shiftada
  const s2reloaded = d.suggestions.find(x => x.id === s2.id);
  if (s2reloaded.status !== 'pending') throw new Error('(c) s2 deveria continuar pending');
  if (newContent.slice(s2reloaded.range.start, s2reloaded.range.end) !== 'entidades públicas') {
    throw new Error('(c) range de s2 não foi shiftada: ' + JSON.stringify(s2reloaded.range)
      + ' slice="' + newContent.slice(s2reloaded.range.start, s2reloaded.range.end) + '"');
  }

  // (d) accept s2 — aplica e fica com o conteúdo final
  global.Suggestions.accept(d, s2.id);
  const finalContent = d.body.items[0].paragraphs[0].content;
  if (!finalContent.includes('estatui o regime-piloto') || !finalContent.includes('entidades do sector público')) {
    throw new Error('(d) s2 não foi aplicada: ' + finalContent);
  }

  // (e) reject — uma 3.ª sugestão rejeitada não deve mexer no content
  const beforeReject = d.body.items[0].paragraphs[0].content;
  const s3 = global.Suggestions.add(d, 'art_1__para_1', 'content',
    { start: 0, end: 12 }, 'A presente lei', { author: 'rev' });
  global.Suggestions.reject(d, s3.id);
  if (s3.status !== 'rejected') throw new Error('(e) reject não mudou status');
  if (d.body.items[0].paragraphs[0].content !== beforeReject) {
    throw new Error('(e) reject mudou o content (não devia)');
  }

  // (f) drift — sugestão sobre originalText que já não existe deve ficar 'stale' ao aceitar
  const s4 = global.Suggestions.add(d, 'art_1__para_1', 'content',
    { start: 0, end: 12 }, 'X', { author: 'rev' });
  // Editar o content directamente — simular um typo do autor que invalida a range
  d.body.items[0].paragraphs[0].content = 'XX' + d.body.items[0].paragraphs[0].content;
  global.Suggestions.accept(d, s4.id);
  if (s4.status !== 'stale') throw new Error('(f) drift devia produzir stale, viu ' + s4.status);

  // (g) Test re-anchor com OVERLAPPING — aceitar uma e ver a outra marcada stale
  Object.keys(_mem).forEach(k => delete _mem[k]);
  const doc2 = global.newDocument('dec-lei');
  doc2.body.items[0].paragraphs[0].id = 'art_1__para_1';
  doc2.body.items[0].paragraphs[0].content = 'abcdefghij';
  global.State.init(doc2);
  const d2 = global.State.get();
  const a = global.Suggestions.add(d2, 'art_1__para_1', 'content', { start: 2, end: 5 }, 'XYZ');
  const b = global.Suggestions.add(d2, 'art_1__para_1', 'content', { start: 4, end: 7 }, 'PQR');  // overlap
  global.Suggestions.accept(d2, a.id);
  const bReloaded = d2.suggestions.find(x => x.id === b.id);
  if (bReloaded.status !== 'stale') throw new Error('(g) overlap não marcou stale');

  console.log(`  OK   Suggestions accept/reject (7 sub-testes: a-g)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL Suggestions: ${e.message}`);
  n_fail++;
}

// 10e. Test Amendment.toAknXmlConsolidated — consolidação + retificação
try {
  Object.keys(_mem).forEach(k => delete _mem[k]);
  // Construir um diploma alvo (DL 50/2026) com 3 artigos
  const target = global.newDocument('dec-lei');
  target.number = '50'; target.year = 2026;
  target.shortTitle = 'Diploma alvo para teste de consolidação.';
  target.adoptionDate = '2026-01-10';
  target.publicationDate = '2026-01-15';
  target.docDate = '2026-01-15'; target.docDateText = '15 de janeiro';
  target.body.items = [
    {
      id: 'art_1', num: 'Artigo 1.º', heading: 'Objeto',
      paragraphs: [{ id: 'art_1__para_1', num: '', content: 'O presente DL estabelece o regime de teste.', subPoints: [] }],
    },
    {
      id: 'art_2', num: 'Artigo 2.º', heading: 'Definições',
      paragraphs: [{ id: 'art_2__para_1', num: '', content: 'Regime A.', subPoints: [] }],
    },
    {
      id: 'art_3', num: 'Artigo 3.º', heading: 'Entrada em vigor',
      paragraphs: [{ id: 'art_3__para_1', num: '', content: 'Entra em vigor em 1 de fevereiro.', subPoints: [] }],
    },
  ];
  target.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-01-10' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-01-12' },
  ];

  // Criar amender + 2 amendments (substituição art_2 + revogação art_3).
  // Amendment.fromTarget aceita o doc do alvo directamente.
  const amender = global.Amendment.fromTarget(target);
  amender.number = '120'; amender.year = 2026;
  amender.publicationDate = '2026-04-15';
  amender.adoptionDate = '2026-04-10';
  amender.docDate = '2026-04-15'; amender.docDateText = '15 de abril';
  amender.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-04-10' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-04-12' },
  ];
  amender.uri = `https://eli.gov.pt/eli/pt/dec-lei/2026/120/pt`;
  global.Amendment.addReplace(amender, 'art_2', {
    id: 'art_2', num: 'Artigo 2.º', heading: 'Definições',
    paragraphs: [{ id: 'art_2__para_1', num: '', content: 'Regime A bis (alterado).', subPoints: [] }],
  }, '2026-05-01');
  global.Amendment.addRevoke(amender, 'art_3', '2026-05-01');

  // (a) Consolidar à data 2026-05-01 (após amendments entrarem em vigor)
  const xmlCons = global.Amendment.toAknXmlConsolidated(amender, '2026-05-01');
  if (!xmlCons.includes('name="consolidation"')) {
    throw new Error('(a) XML sem FRBRdate name="consolidation"');
  }
  if (!xmlCons.includes('FRBRversionNumber value="2"')) {
    throw new Error('(a) versão FRBR não foi incrementada');
  }
  if (!xmlCons.includes('2026-05-01')) {
    throw new Error('(a) URI Expression não usa data de consolidação');
  }
  if (!xmlCons.includes('Regime A bis')) {
    throw new Error('(a) conteúdo do amendment não foi aplicado');
  }
  if (!xmlCons.includes('<passiveModifications>')) {
    throw new Error('(a) <passiveModifications> não preenchido');
  }
  if (!xmlCons.includes('type="substitution"')) {
    throw new Error('(a) textualMod type="substitution" em falta');
  }
  if (!xmlCons.includes('type="repeal"')) {
    throw new Error('(a) textualMod type="repeal" em falta');
  }
  fs.writeFileSync(path.join(OUT, 'consolidated-frbr.akn.xml'), xmlCons);

  // (b) Consolidar à data 2026-02-01 (ANTES dos amendments — só vigentes os null)
  const xmlEarly = global.Amendment.toAknXmlConsolidated(amender, '2026-02-01');
  if (xmlEarly.includes('Regime A bis')) {
    throw new Error('(b) amendment com effectiveDate=2026-05-01 não devia aplicar em 2026-02-01');
  }
  if (!xmlEarly.includes('Regime A.')) {
    throw new Error('(b) conteúdo original não preservado');
  }

  // (c) Retificação — kind='rectification' produz FRBRdate name="rectification"
  const xmlRect = global.Amendment.toAknXmlConsolidated(amender, '2026-05-01', { kind: 'rectification' });
  if (!xmlRect.includes('name="rectification"')) {
    throw new Error('(c) FRBRdate name="rectification" em falta');
  }
  if (!xmlRect.includes('type="rectification"')) {
    throw new Error('(c) textualMod type="rectification" em falta');
  }
  fs.writeFileSync(path.join(OUT, 'rectification.akn.xml'), xmlRect);

  // (d) Validação de inputs
  try {
    global.Amendment.toAknXmlConsolidated(amender, 'invalid');
    throw new Error('(d) deveria rejeitar data inválida');
  } catch (e) {
    if (!e.message.includes('isoDate')) throw e;
  }

  console.log(`  OK   Amendment.toAknXmlConsolidated (4 sub-testes: a-d; ${xmlCons.length}b consolidated + ${xmlRect.length}b rectification)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL Amendment.toAknXmlConsolidated: ${e.message}`);
  n_fail++;
}

// 10f. Test hierarquia profunda — round-trip de body com chapter/section
try {
  Object.keys(_mem).forEach(k => delete _mem[k]);
  // Carregar o CIRS excerpt (corpus #11) e fazer round-trip via ImportParser
  const cirsPath = path.join(ROOT, '..', 'corpus', 'dec-lei', 'codigo-irs-excerpt.akn.xml');
  if (!fs.existsSync(cirsPath)) {
    throw new Error(`(a) fixture não encontrada em ${cirsPath}`);
  }
  const xmlIn = fs.readFileSync(cirsPath, 'utf8');
  // ImportParser.parseAknXml usa DOMParser; em Node precisamos shim minimal.
  // jsdom (já dep do projeto pelos UI tests) — load on demand.
  if (typeof global.DOMParser === 'undefined') {
    try {
      const { JSDOM } = require('jsdom');
      const dom = new JSDOM('');
      global.DOMParser = dom.window.DOMParser;
    } catch (e) {
      throw new Error('(a) DOMParser não disponível (jsdom em falta): ' + e.message);
    }
  }
  const parsed = global.ImportParser.parseAknXml(xmlIn);
  if (parsed.bodyKind !== 'hierarchic') {
    throw new Error(`(a) parseAknXml não detectou hierarchic, viu ${parsed.bodyKind}`);
  }
  if (!parsed.bodyItems || parsed.bodyItems.length !== 1) {
    throw new Error(`(a) esperava 1 container raiz (cap_1), vi ${parsed.bodyItems?.length}`);
  }
  const cap = parsed.bodyItems[0];
  if (cap.containerType !== 'chapter' || cap.id !== 'cap_1') {
    throw new Error(`(a) container raiz mal parseado: type=${cap.containerType} id=${cap.id}`);
  }
  if ((cap.items || []).length !== 2) {
    throw new Error(`(a) capítulo deve ter 2 secções, viu ${cap.items?.length}`);
  }
  const sec1 = cap.items[0];
  if (sec1.containerType !== 'section') throw new Error('(a) primeira section mal parseada');

  // (b) toDocState produz body.kind='hierarchic'
  const doc = global.ImportParser.toDocState(parsed);
  if (doc.body.kind !== 'hierarchic') {
    throw new Error(`(b) toDocState não preservou hierarchic, viu ${doc.body.kind}`);
  }

  // (c) Re-export para XML e validar contra XSD
  const xmlOut = global.AknExport.toXml(doc);
  if (!xmlOut.includes('<chapter eId="cap_1">')) {
    throw new Error('(c) re-export sem <chapter>');
  }
  if (!xmlOut.includes('<section eId="cap_1__sec_1">')) {
    throw new Error('(c) re-export sem <section>');
  }
  if (!xmlOut.includes('<article eId="art_1">')) {
    throw new Error('(c) re-export sem <article art_1>');
  }
  fs.writeFileSync(path.join(OUT, 'cirs-roundtrip.akn.xml'), xmlOut);

  // (d) Estatísticas para confirmar — 3 articles total no XML
  const artCount = (xmlOut.match(/<article eId=/g) || []).length;
  if (artCount !== 3) throw new Error(`(d) esperava 3 articles no XML re-exportado, viu ${artCount}`);

  console.log(`  OK   Hierarchic body round-trip (4 sub-testes: a-d; ${xmlOut.length}b CIRS re-exported)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL Hierarchic body round-trip: ${e.message}`);
  n_fail++;
}

// 10g. Test State containers — addContainer / moveContainerUp/Down / removeContainer
try {
  Object.keys(_mem).forEach(k => delete _mem[k]);
  const doc = global.newDocument('dec-lei');
  doc.number = '888'; doc.year = 2026;
  doc.shortTitle = 'Containers test.';
  // 4 artigos baseline
  doc.body.items = ['A', 'B', 'C', 'D'].map((tag, i) => ({
    id: `art_${i+1}`, num: `Artigo ${i+1}.º`, heading: `Artigo ${tag}`,
    paragraphs: [{ id: `art_${i+1}__para_1`, num: '', content: `Conteúdo ${tag}.`, subPoints: [] }],
  }));
  global.State.init(doc);

  // (a) ensureHierarchicBody promove articles → hierarchic
  global.State.ensureHierarchicBody();
  let d = global.State.get();
  if (d.body.kind !== 'hierarchic') {
    throw new Error('(a) ensureHierarchicBody falhou; viu ' + d.body.kind);
  }
  if (d.body.items.length !== 4) {
    throw new Error('(a) artigos perdidos no upgrade');
  }

  // (b) addContainer chapter no root
  const capId = global.State.addContainer('chapter');
  d = global.State.get();
  // Esperar: 4 artigos + 1 capítulo (sem filhos ainda)
  if (d.body.items.length !== 5) {
    throw new Error('(b) esperava 5 items após addContainer, vi ' + d.body.items.length);
  }
  const cap = d.body.items.find(it => it.containerType === 'chapter');
  if (!cap) throw new Error('(b) chapter não encontrado');
  if (cap.id !== 'cap_1') throw new Error('(b) eId esperado cap_1, vi ' + cap.id);
  if (cap.num !== 'CAPÍTULO I') throw new Error('(b) num esperado "CAPÍTULO I", vi ' + cap.num);

  // (c) addContainer section dentro do chapter
  global.State.addContainer('section', { parentEId: 'cap_1' });
  d = global.State.get();
  const cap1 = d.body.items.find(it => it.id === 'cap_1');
  if (!cap1 || !cap1.items || cap1.items.length !== 1) {
    throw new Error('(c) secção não foi adicionada dentro do capítulo');
  }
  const sec = cap1.items[0];
  if (sec.id !== 'sec_1' || sec.num !== 'SECÇÃO I') {
    throw new Error('(c) section eId/num errados: ' + JSON.stringify({id: sec.id, num: sec.num}));
  }

  // (d) updateContainer altera heading
  global.State.updateContainer('cap_1', { heading: 'Disposições gerais' });
  d = global.State.get();
  if (d.body.items.find(it => it.id === 'cap_1').heading !== 'Disposições gerais') {
    throw new Error('(d) updateContainer falhou');
  }

  // (e) Renumeração mantém artigos flat (art_1..art_4)
  const arts = d.body.items.filter(it => it.containerType === undefined);
  if (arts.length !== 4) throw new Error('(e) esperava 4 artigos no root, vi ' + arts.length);
  if (arts.map(a => a.id).join(',') !== 'art_1,art_2,art_3,art_4') {
    throw new Error('(e) artigos não estão flat: ' + arts.map(a => a.id).join(','));
  }

  // (f) addContainer chapter — esperar cap_2 (counter por tipo)
  global.State.addContainer('chapter');
  d = global.State.get();
  const caps = d.body.items.filter(it => it.containerType === 'chapter');
  if (caps.length !== 2) throw new Error('(f) esperava 2 chapters');
  if (!caps.find(c => c.id === 'cap_2' && c.num === 'CAPÍTULO II')) {
    throw new Error('(f) cap_2 não numerado correctamente');
  }

  // (g) removeContainer com keepChildren=true promove filhos
  global.State.removeContainer('cap_1', { keepChildren: true });
  d = global.State.get();
  // A secção sec_1 que estava em cap_1 deve agora ser sibling no root
  // (mas renumerada para sec_1 ainda — única secção).
  // cap_2 também é renumerado para cap_1 (único chapter restante).
  const newCaps = d.body.items.filter(it => it.containerType === 'chapter');
  if (newCaps.length !== 1 || newCaps[0].id !== 'cap_1') {
    throw new Error('(g) cap_2 não foi renumerado para cap_1 após remove');
  }
  const orphanSec = d.body.items.find(it => it.containerType === 'section');
  if (!orphanSec) {
    throw new Error('(g) secção órfã perdida no promote');
  }

  // (h) moveContainerUp move chapter para o topo
  global.State.addContainer('chapter');  // cap_2
  global.State.moveContainerUp(d.body.items.find(c => c.containerType === 'chapter')?.id || 'cap_1');
  // Apenas confirmar que renumber atribui IDs sequenciais sem crash
  d = global.State.get();
  const finalCaps = d.body.items.filter(it => it.containerType === 'chapter');
  if (finalCaps.length !== 2) throw new Error('(h) esperava 2 caps após add+move');

  // (i) Para exportar XML válido contra Schematron (STR-0005: capítulo deve
  //     ter ≥1 artigo/secção), populamos manualmente o doc de teste com 1
  //     capítulo contendo 1 secção contendo 1 artigo. Os mutators de container
  //     só inserem containers vazios — promoção de artigos para dentro de
  //     containers fica para v0.1.3 (move-into-container).
  d.body = {
    kind: 'hierarchic',
    items: [{
      id: 'cap_1', containerType: 'chapter',
      num: 'CAPÍTULO I', heading: 'Disposições gerais',
      items: [{
        id: 'cap_1__sec_1', containerType: 'section',
        num: 'SECÇÃO I', heading: 'Disposições preliminares',
        items: [{
          id: 'art_1', num: 'Artigo 1.º', heading: 'Objeto',
          paragraphs: [{ id: 'art_1__para_1', num: '', content: 'Teste de container.', subPoints: [] }],
        }],
      }],
    }],
  };
  d.number = '888'; d.year = 2026;
  d.shortTitle = 'Test containers'; d.adoptionDate = '2026-01-10';
  d.publicationDate = '2026-01-15'; d.docDate = '2026-01-15'; d.docDateText = '15 de janeiro';
  d.signatures = [
    { role: 'countersignature', as: 'primeiro-ministro', name: 'PM', date: '2026-01-10' },
    { role: 'promulgation', as: 'presidente-republica', name: 'PR', date: '2026-01-12' },
  ];
  const xml = global.AknExport.toXml(d);
  if (!xml.includes('<chapter eId="cap_1">')) {
    throw new Error('(i) XML sem <chapter eId="cap_1">');
  }
  fs.writeFileSync(path.join(OUT, 'containers-roundtrip.akn.xml'), xml);

  console.log(`  OK   State containers (9 sub-testes: a-i; ${xml.length}b)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL State containers: ${e.message}`);
  n_fail++;
}

// 11. Test Snapshots / Milestones — fase + listByPhase + getPhasesForActType
try {
  const doc = global.newDocument('dec-lei');
  doc.number = '500'; doc.year = 2026;
  doc.shortTitle = 'Diploma para testar milestones.';
  doc.body.items[0].heading = 'Objeto';
  doc.body.items[0].paragraphs[0].content = 'Conteúdo inicial.';
  global.State.init(doc);

  // 11a. Backwards compat — save sem opts continua a funcionar
  const s1 = global.Snapshots.save('snap-sem-fase');
  if (s1.phase) throw new Error('(a) snap sem opts não devia ter phase');

  // 11b. Save com fase explícita
  const s2 = global.Snapshots.save('m1', { phase: 'rascunho' });
  if (s2.phase !== 'rascunho') throw new Error('(b) phase não persistida');

  // 11c. Save com note via string (compat de 2.º arg como string)
  const s3 = global.Snapshots.save('com-nota', 'Nota livre.');
  if (s3.note !== 'Nota livre.') throw new Error('(c) compat note-string falhou');

  // 11d. Save 2.ª milestone com mesma fase + 1 noutra fase
  global.Snapshots.save('m2', { phase: 'rascunho' });
  global.Snapshots.save('m3', { phase: 'consulta-pública' });

  // 11e. listByPhase agrupa
  const m = global.Snapshots.listByPhase();
  const r = m.get('rascunho') || [];
  const c = m.get('consulta-pública') || [];
  const semFase = m.get('sem-fase') || [];
  if (r.length !== 2) throw new Error(`(e) esperava 2 em 'rascunho', vi ${r.length}`);
  if (c.length !== 1) throw new Error(`(e) esperava 1 em 'consulta-pública', vi ${c.length}`);
  if (semFase.length !== 2) throw new Error(`(e) esperava 2 'sem-fase', vi ${semFase.length}`);

  // 11f. Ordenação dentro do bucket (cronológica asc)
  if (r[0].date > r[1].date) throw new Error('(f) bucket não está em ordem asc');

  // 11g. getPhasesForActType — vocabulário esperado para dec-lei
  const phases = global.Snapshots.getPhasesForActType('dec-lei');
  if (!phases.includes('consulta-pública') || !phases.includes('promulgação')) {
    throw new Error('(g) vocabulário dec-lei incompleto: ' + JSON.stringify(phases));
  }

  // 11h. getPhasesForActType — fallback por prefixo (e.g. 'dlr-acores' → 'dlr')
  const pDlr = global.Snapshots.getPhasesForActType('dlr-acores');
  if (!pDlr.includes('aprovação-ALR')) {
    throw new Error('(h) fallback de prefixo falhou: ' + JSON.stringify(pDlr));
  }

  // 11i. getPhasesForActType — actType desconhecido → vocabulário common
  const pUnk = global.Snapshots.getPhasesForActType('inexistente');
  if (!pUnk.includes('rascunho')) {
    throw new Error('(i) fallback common falhou: ' + JSON.stringify(pUnk));
  }

  // 11j. delete + listByPhase — o entry desaparece do bucket
  global.Snapshots.delete(s2.id);
  const m2 = global.Snapshots.listByPhase();
  if ((m2.get('rascunho') || []).length !== 1) {
    throw new Error('(j) delete não removeu do bucket');
  }

  console.log(`  OK   Snapshots milestones (10 sub-testes: a-j)`);
  n_ok++;
} catch (e) {
  console.log(`  FAIL Snapshots milestones: ${e.message}`);
  n_fail++;
}

const total = cases.length + 21;
console.log(`\n${n_ok}/${total} files generated.`);
console.log(`Next: validate with akn-pt:`);
console.log(`  python -m akn_pt batch editor/.smoke-output`);
process.exit(n_fail ? 1 : 0);
